### ISSUE TITLE
Tus Research Tasks: Resumable Upload Expiration with Tus and Azure

### ISSUE THREAD

**Issue by mkrystof** [CDCgov/data-exchange-upload#38]
### Tasks
- [x] Determine where tus intermediate files are stored
- [x] Determine how to set expiration of tus uploads.  See [Tus upload expirations](https://tus.io/protocols/resumable-upload.html#expiration)

**Comment by cfarmer-fearless** [comment]
Adding a couple issues in the tusd repo discussing this topic:
https://github.com/tus/tusd/issues/176
https://github.com/tus/tusd/issues/435

**Comment by cfarmer-fearless** [comment]
Report document for review:
https://cdc.sharepoint.com/:w:/r/teams/CDC-Data-Exchange/Shared%20Documents/Operations/Resumable%20Upload%20Expiration%20with%20Tus%20and%20Azure.docx?d=w2b392e89b77b4fac8a640ce98766956b&csf=1&web=1&e=0p3scj

**Comment by rmharrison** [comment]
Read and accepted.

Briefly...
- Determine where tus intermediate files are stored ==> Azure Blob Storage as uncommitted chunks
- Determine how to set expiration of tus uploads.  See [Tus upload expirations](https://tus.io/protocols/resumable-upload.html#expiration) ==> 2 weeks by default from Azure Blob garbage collection
