### ISSUE TITLE
Demonstrate moving committed blobs from DEX Storage Account to EDAV storage account

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-upload#47]
### Task Goals

- Demo bulk uploading files via a tus client and show the completed upload in the EDAV storage account.
- Demo combining tus payload and info files into single blob file with metadata attached
- Demo routing program files into new blob containers in DeX from the program ID metadata
- Demo copying files from DeX program containers to EDAV program containers.  The routing of blob container names in DeX containers should be 1:1 with the program ID and show up under the same container name in EDAV.

**Flow Overview**

DeX storage -> Upload event -> Function App combines payload/metadata into single file and copies to new DeX container under program name (routing) -> Blob file copied to EDAV storage

**Demo Process**
1. Program A uploads to tus
1. Upload completes and shows up in the catch-all single blob container of the DeX storage account
1. Routing event is triggered from the upload completions
1. Function app receives upload event and does the routing to a new DeX container based on program ID.  Function app combines the tus payload file with the .info file.
1. [Azure object replication](https://learn.microsoft.com/en-us/azure/storage/blobs/object-replication-configure?tabs=portal) copies the file from program A container in DeX storage account to program A container in EDAV storage account
1. Success!

**Comment by mkrystof** [comment]
### Infrastructure Setup Steps

1. Create an Azure Event Grid System Topic:
   - Topic Types: Storage Accounts (Blob & GPv2)
   - Subscription: OCIO-EDEDEV-C1
   - Resource Group: ocio-ede-dev-moderate-hl7-rg
   - Resource: dataexchangedev
   - Name: **bulk-file-uploaded-topic**
   - Location: eastus
2. Create an Azure Function App:
   - Subscription: OCIO-EDEDEV-C1
   - Resource Group: ocio-ede-dev-moderate-hl7-rg
   - Function App Name: ocio-ede-dev-bulk-file-upload-processor
   - Publish: Code
   - Runtime stack: .NET
   - Version: 6
   - Region: East US
   - Operating System: Windows
   - Plan type: Consumption (Serverless)
3. Create an app function within the newly created ocio-ede-dev-bulk-file-upload-processor function app.
   > Note this function app was created by Visual Studio automatically.  Be sure to map the step below to the correct Function name you use in the code.
   > 
   > e.g. `BulkFileUploadFunction`
4. Inside the newly created bulk-file-uploaded-topic, create an Event Subscription:
   - Name: bulk-file-uploaded-event
   - Event Schema: Event Grid Schema
   - Topic Type: Storage account
   - Source Resource: dataexchangedev
   - Topic Name: bulk-file-uploaded-topic
   - Filter to Event Types: Blob Created
   - Subject Filters:
     - [x] Enable subject filtering
       - Subject Begins With: /blobServices/default/containers/bulkuploads
       - Advanced Filters:
         - Key: subject
         - Operator: String does not contain
         - Value: .info
        > This advanced filter makes it so only the payload file triggers the event, not the `.info` files.
   - Endpoint Type: Azure Function
   - Endpoint: Select an endpoint (enter the following)
     - Subscription: OCIO-EDEDEV-C1
     - Resource Group: ocio-ede-dev-moderate-hl7-rg
     - Function app: ocio-ede-dev-bulk-file-upload-processor
     - Slot: Production
     - Function: BulkFileUploadFunction
