### ISSUE TITLE
Metadata Configuration Files

### ISSUE THREAD

**Issue by jmann2817** [CDCgov/data-exchange-upload#56]
Metadata Configuration Files
Metadata configuration files will be used by the tusd pre-create file hook, which is a blocking executable called before the file upload is accepted. The pre-create executable can examine the metadata provided at the start of the upload and indicate to tusd whether the upload should be allowed to proceed or return an error to the client.

Example: Routine Immunization metadata

NDLP metadata fields

**Required** meta_destination_id = "NDLP"
meta_ext_source = "IZGW"
meta_ext_sourceversion = "V2022-09-09"
**Required** meta_ext_event = "routineImmunization"
meta_ext_entity = Submitting entity code, always 3 digits; e.g. NYA, CV1
meta_username = Username of user who uploaded the file. This will be the name of the service account if the upload is system-to-system.
meta_ext_objectkey = UUID
meta_ext_filename = Name of the file uploaded by the user. File and extension should be named in accordance with guidelines outlined in the Data Use Agreement (DUA) for routine immunization.
Metadata is typically provided as JSON by tus clients when the file is uploaded but is dependent on the tus client for the language used.

Metadata Config File Location
Important!
Need to ~very~ verify that a file volume can be mounted when the tusd server docker image is started. In doing so, the metadata config files can be stored in an Azure blob storage container and used directly by tus file hooks facilitating easy management of metadata configurations by program. This looks to be possible from this Tutorial: Create an Azure Files storage mount in Azure Container Apps.

Metadata in Zipped Files
What if the file is a zip file? The metadata should reflect the zip file only, not the contents within the zip file. It will be the responsibility of programs' downstream processing to unzip the file, determine the validity of contents and any further processing or determination of metadata. For example, one program uses an Excel .xls file within the zip file to indicate the metadata contents by filename.

**Comment by mkrystof** [comment]
[PR 59](https://github.com/CDCgov/data-exchange-upload/pull/59) contains the code changes.

**Comment by mkrystof** [comment]
### File Share setup on dataexchangedev storage account

1. Create container in dataexchangedev:
   - Name: tusd-hook-files
2. Go to the app service/container app Configuration.
3. Select Path Mappings and add New Azure Storage Mount:
   - Name: tusd-file-hooks
   - Configuration options: Basic
   - Storage accounts: dataexchangedev
   - Storage type: Azure Blob
   - Storage container: tusd-file-hooks
   - Mount path: /tusd-file-hooks

**Comment by mkrystof** [comment]
Completed under [PR 59](https://github.com/CDCgov/data-exchange-upload/pull/59), which has been approved and merged.
