### ISSUE TITLE
Spike: EDAV metadata source of truth synchronization

### ISSUE THREAD

**Issue by mkrystof** [CDCgov/data-exchange-upload#64]
### Problem definition
The use-case of ingesting large amounts of metadata into ADF/Databricks from Azure Blob Storage where metadata is attached to the payload is a problem. With the current DEX design, metadata is associated with the file in Blob Storage; however, reading metadata from Azure Blob Storage is inefficient in Spark.

### Spike purpose
The DEX team is looking into solutions to provide a source of truth for metadata on files so that centers/programs can do rapid processing, in an effort to offload programs and centers from having to match file metadata themselves.

In the event EDAV does not support nor intend to support a solution then a DEX solution may be needed.

### Definition of Done
This spike will determine whether DEX can maintain a separate data store for the metadata that can stay in sync with the source of truth (the Azure metadata on the payload in the EDAV storage account).

Provide a detailed design and sample solution that demonstrates the ability to:
- Synchronize file-level metadata
  * Option: HIVE metastore (similiar to AWS Glue)
  * Option: Cosmos
  * Option: Another backing store that can easily be ingested into ADF/Databricks
- Ensure that if metadata is updated in the source of truth (metadata on a file in the EDAV storage account), that
  * The metadata in the separate metadata storage is immediately synced
  * Update operations are atomic so there is no possibility of a mismatch - either the update operation completes for both or fails for both

**Comment by rmharrison** [comment]
FFR, blurb prior to edits...

>### Problem definition
>The use-case of ingesting large amounts of data into ADF/Databricks from Azure blob storage where metadata is attached to the payload is a problem.  With the current DEX design, metadata is associated with the file in blob storage and reading metadata from Azure blob storage is very inefficient in Spark.
>
>### Spike purpose
>The DEX team is looking into solutions to provide a source of truth for metadata on files so that centers/programs can do rapid processing, in an effort to offload programs and centers from having to match file metadata themselves.
>
>In the event EDAV does not support nor intend to support a solution then a DEX solution may be needed.
>
>### Definition of done
>This spike will determine whether DEX can maintain a separate data store for the metadata that can stay in sync with the source of truth, which is the payload+metadata file stored in the EDAV storage account.
>
>Provide a detailed design and sample solution that demonstrates the ability to:
>- Synchronize file-level metadata in Cosmos or other backing store that can easily be ingested into ADF/Databricks
>- Ensure that if metadata is updated in the source of truth (the EDAV storage account), that
>    1. The metadata in the separate metadata storage is immediately synced
>    1. Update operations are atomic so there is no possibility of a mismatch - either the update operation completes for both or fails for both
